FROM registry.access.redhat.com/ubi8/ubi as builder
COPY java-17-openjdk-17.0.7.0.7-1.portable.jre.el.x86_64.tar.gz /
RUN tar -xf java-17-openjdk-17.0.7.0.7-1.portable.jre.el.x86_64.tar.gz && \
    rm java-17-openjdk-17.0.7.0.7-1.portable.jre.el.x86_64.tar.gz && \
    mv java-* /opt/openjre-17.0.7
FROM registry.access.redhat.com/ubi8-micro:8.9-15
COPY --from=builder /opt/openjre-17.0.7 /usr/lib/openjre-17.0.7
ENV JAVA_HOME=/usr/lib/openjre-17.0.7
ENV PATH=$PATH:$JAVA_HOME/bin
ADD https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v2.2.0/opentelemetry-javaagent.jar opentelemetry-javaagent.jar
COPY config /code/config
COPY target/lib /code/lib
COPY startup.sh /code
ENTRYPOINT [ "/bin/bash", "/code/startup.sh" ]